apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-service-config
  namespace: microservices
  labels:
    app: identity-service
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5010"
