apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: microservices
  labels:
    app: payment-service
data:
  NODE_ENV: "production"
  PORT: "50012"
  MONGO_DB_NAME: "payments_db"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  LOKI_URL: "http://loki:3100"
  LOG_LEVEL: "info"
  SERVICE_NAME: "PaymentService"
  SERVICE_VERSION: "1.0.0"
