apiVersion: v2
name: microservices-umbrella
description: Umbrella chart for deploying all microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: order-service
    version: "0.1.0"
    repository: "file://../order-service"
  - name: payment-service
    version: "0.1.0"
    repository: "file://../payment-service"
  - name: identity-service
    version: "0.1.0"
    repository: "file://../identity-service"

keywords:
  - microservices
  - saga
  - grpc
maintainers:
  - name: DevOps Team
