apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - namespace.yaml
  # ConfigMaps
  - configmaps/order-service-config.yaml
  - configmaps/payment-service-config.yaml
  - configmaps/identity-service-config.yaml
  # Databases
  - databases/postgres.yaml
  - databases/mongodb.yaml
  # Services
  - services/order-service.yaml
  - services/payment-service.yaml
  - services/identity-service.yaml
  # Deployments
  - deployments/order-service.yaml
  - deployments/payment-service.yaml
  - deployments/identity-service.yaml

commonLabels:
  app.kubernetes.io/part-of: microservices
  app.kubernetes.io/managed-by: kustomize
